### PR TITLE
Don't crash on writing big tags

### LINKED ISSUE #40: Support modern node.js versions
Currently building/testing etc. the anonymiser only works using Node 12, this seems to be due to outdated dependencies, particularly, [old Webpack](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported/69691525#69691525) that [hard-codes using `md4` hashes](https://github.com/webpack/webpack/blob/cd4af164784f3938353102179adfcbcf8f53949d/lib/optimize/ConcatenatedModule.js#L563) which were deprecated/removed in later node.js versions.

### PR DESCRIPTION
**Pull request by flaki**
This is a general fix for writing tags that are too big according to the DICOM standard. The previous fix #42 only fixed a specific tag, but since then we have found other tags and VRs that exhibit this issue.

This fix takes care by copying the offending tags verbatim, it does log a console message as a warning.

Included in these changes are the update/modernization of the dependencies and the code base. Swapped out Webpack to ESBuild to run the local development server and updated all dependencies. This fixes #40 .

### CODE REVIEW

File: lib/Anon.js [hunk 1]
```diff
@@ -191,7 +193,7 @@ export default function anonymize(dcm) {
             var value = tagValues[id];
             if (typeof value === "string" && value.match(/eE/) === null) {
                 tagValues[id] = value.substr(0, 16);
-                console.warn("Warning: clipped Slice Location value from '" + value + "' to '" + tagValues[id] + "'.");
+                console.warn("Warning: clipped Slice Location value from '".concat(value, "' to '").concat(tagValues[id], "'."));
```
Comment (DanielHeath) [inline lib/Anon.js:196]: We don't target anything that doesn't support backticks - why is `esbuild` generating such bloated code?



Perhaps `esbuild lib/browser.js --bundle --target esnext --sourcemap --outfile=docs/js/main.js`

Comment (DanielHeath) [reply lib/Anon.js:196]: Ahh, I see - we're using `tsc` to compile typescript to js, then using `esbuild` to compile the results.

**Review by DanielHeath — APPROVED** [review]
If you're happy with my changes to this branch (and it works with the main app), merge away.
